{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyOYIqowDVmiq9d83IUYFVcN"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"Pw9Ord52BC0d","executionInfo":{"status":"ok","timestamp":1752347046643,"user_tz":-330,"elapsed":6340,"user":{"displayName":"Aditya Naik","userId":"02494853453438898824"}},"outputId":"a895066a-e392-4c07-9562-6fb32cba6225"},"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting sklearn\n","  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)\n","  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","  \n","  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n","  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","  \u001b[31m╰─>\u001b[0m See above for output.\n","  \n","  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25herror\n","\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n","\n","\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n","\u001b[31m╰─>\u001b[0m See above for output.\n","\n","\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n","\u001b[1;36mhint\u001b[0m: See above for details.\n"]}],"source":["pip install sklearn\n"]},{"cell_type":"code","source":["from sklearn.datasets import load_iris"],"metadata":{"id":"WJVhH1RDBJTq","executionInfo":{"status":"ok","timestamp":1752347114232,"user_tz":-330,"elapsed":26,"user":{"displayName":"Aditya Naik","userId":"02494853453438898824"}}},"execution_count":7,"outputs":[]}]}